### ISSUE TITLE
Direct editing and Find&Replace

### ISSUE THREAD

**Issue by FeBe95** [facelessuser/HexViewer#30]
Is it possible to add a setting to directly edit (overwrite) the hex code and its ASCII text translation? Like with a normal text and you hit the "Insert"-key on your keyboard.
Also it would be nice to be able to use the build-in search&replace function for hex and ASCII.
And is it necessary to handle the files separately as .hex files? Couldn't the editing process be done in the file directly?

**Comment by facelessuser** [comment]
> Is it possible to add a setting to directly edit (overwrite) the hex code and its ASCII text translation? Like with a normal text and you hit the "Insert"-key on your keyboard.

Not currently.  This is mainly because the format of the text is very important for maintaining the other functionality of HexViewer.  Giving users such freedom would require a lot more work for me on the backend.  It just adds a lot more complexity that I just am not currently motivated to even try taking on.

> Also it would be nice to be able to use the build-in search&replace function for hex and ASCII.

Again, the is related to the first question a above.

> And is it necessary to handle the files separately as .hex files? Couldn't the editing process be done in the file directly?

I don't understand the question.  I needed to display info (address, actual byte data, and ascii representation) in a text format that I could easily manipulate and trigger functionality off the scoped syntax via my custom syntax language.  I don't see how you would get all that information without processing the data and injecting addresses and ascii data.  Does it have to be `.hex`?  No I guess I could have used anything, but I need a process format.  I actually also have a personal script that I can use to generate `.hex` from bin files outside of HexViewer.  And that way I can open those up in Sublime as well and get HexViewer functionality, so it is useful for me.

**Comment by FeBe95** [comment]
Okay, I see your point.The last question was badly asked: I don't know if Sublime supports such kind of file handling and I was using Notepad++ for a long time and the HexEditor.dll plugin just changes the interface of the text area (column captions etc.), and when I save the file while in hex mode, it gets saved with its normal file name:
![lorem hex](https://cloud.githubusercontent.com/assets/7470739/6315812/55b0ea82-ba0f-11e4-8b5c-3cb6957b54ff.png)
DLL-Plugins are probably more "powerful" than Python plugins.
This plugin also allows to edit directly and search&replace.

Plugin-URL: http://sourceforge.net/projects/npp-plugins/files/Hex%20Editor/Hex%20Editor%20Plugin%20v0.9.5/

**Comment by facelessuser** [comment]
It should save it with its real name as I track the real name if the hex
view if it was generated from an actual file that exists on disk.

**Comment by FeBe95** [comment]
* open a file (e.g. txt)
* toggle hex view
* edit hex/ascii through edit panel
When I now hit save (disabled through menu, but ctrl+s works) it wants to save the .hex file. Disabling the hex mode without discarding changes is not possible. Just found out that "Exporting Bin" works as "Save" should, am I right?

**Comment by facelessuser** [comment]
> When I now hit save (disabled through menu, but ctrl+s works) it wants to save the .hex file. Disabling the hex mode without discarding changes is not possible. Just found out that "Exporting Bin" works as "Save" should, am I right?

Correct, export is what you want.  I did just notice though that after exporting it doesn't seem to clear the internal "dirty" flag, so when you toggle back it will ask if you want to discard edits.  As edits have already been exported, you aren't really losing anything, but I need to fix that (I don't often edit bin files so I don't know when this creeped in, but I view hex files a lot).

**Comment by facelessuser** [comment]
Found the issue, it creeped in when I started threading some stuff.  Release 2.0.1 will take care of the "dirty" flag issue https://github.com/facelessuser/HexViewer/releases/tag/st3-2.0.1.  When Package Control updates your package, it should no longer be a problem.

**Comment by FeBe95** [comment]
Okay thank you for your support!

**Comment by facelessuser** [comment]
No problem.
