### ISSUE TITLE
Change option 'Show Hex Inspector' to 'Toggle Hex Inspector'

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [facelessuser/HexViewer#31]
Can we change the 'Show Hex Inspector' to 'Toggle Hex Inspector' so that we can hide the Hex Inspector also. 

Also we want this Hex Inspector to be shown only on that file which has the HexViewer Enabled. but it is getting shown on each and every other tab too..

**Comment by facelessuser** [comment]
> Can we change the 'Show Hex Inspector' to 'Toggle Hex Inspector' so that we can hide the Hex Inspector also.

It could be added, but I don't really think that is necessary.  If you hit the escape key, Sublime dismisses panels.

> Also we want this Hex Inspector to be shown only on that file which has the HexViewer Enabled. but it is getting shown on each and every other tab too.

Again, I would just hit escape, its what I do.  Panels aren't really view specific, they are window specific.  I don't really track if the inspector window is up because it is difficult to check when people dismiss it.
