### ISSUE TITLE
Getting "HexViewer: View does not exist on disk!" error

### ISSUE THREAD

**Issue by brosiusad** [facelessuser/HexViewer#39]
When I try to use "Toggle Hex View", I get this error and HexViewer is unusable.

Mac OSX 10.11.3
ST3 build 3103

**Comment by facelessuser** [comment]
Well I doubt it is totally unusable, but unusable for just that view.  As the error states, HexViewer works on views that exist on disk.  To read the binary data, HexViewer needs to read the file raw because Sublime will handle reading endianness, line ending normalization, striping out BOMs etc. which will change the result from the way it might look truly on disk.

HexViewer is meant to read binary files, not transient buffers that exist only in memory.

**Comment by facelessuser** [comment]
I am assuming your question was answered?  I'm going to go ahead and close this issue, but feel free to reopen and elaborate further if your question wasn't answered.

**Comment by orcinus** [comment]
You should really consider changing this error message.
As it is, i'm betting 90% of the users who hit it go googling until they find this issue.

**Comment by facelessuser** [comment]
I am open to pull requests.  At times I am quite busy, so things like this aren't a high priority.  It is on my list, but low on the list.

**Comment by orcinus** [comment]
Done.

**Comment by facelessuser** [comment]
Thanks!

**Comment by orcinus** [comment]
No prob!
