### ISSUE TITLE
We have groups_byte_by_bits. Can we have endianess setting for that?

### ISSUE THREAD

**Issue by charlie388** [facelessuser/HexViewer#45]
As title.
I know the Hex Inspector can being Big/Little endian mode. It let user check value easily.
Sometime I need to check machine code( e.g. ARM processor). It's word/dword boundary placing machine code. If this plugin can switch byte order, it will quite helpful for examining the machine code manually.
e.g. 
3456 7890  -->  big endian
5634 9078  -->  little endian

34567890  12345678  -->  big endian
90785634  78563412  -->  little endian

The Notepad++ has plugin "Hex Editor". In that options has "Start Layout" tab can do this well.

**Comment by facelessuser** [comment]
You'd think I'd already have something like this in since I work with ARM processors.  Just haven't got around to it yet.  Haven't quite worked out how I would want it work, but I will put it on my list.  Can't promise when I'll get around to it though.

**Comment by facelessuser** [comment]
It's been a while since this issue was first opened. HexViewer currently views butterfly in the order they are in binary file. If they have big endianness they are translated with bytes in big endian format. If they are in little endian, they are viewed with little. Currently, we can't force a little endian file to be viewed in big endian format.

The inspector though can be told what format the file is in and translate bytes accordingly to their numerical value. For me, this has made the need for reformatting the default display unnecessary. I'm usually looking at but files in emulators and debuggers in their default endian format anyways, so I've never needed to specifically have HexViewer do anything different.

As it has been over there years since this issue was requested, I guess it is clear that this isn't a feature I have a strong need for, which is why it hasn't received any traction. If someone is willing to do the work via pull request, I may consider it for inclusion, but as things stand currently, I don't plan on adding this. For this reason, I will close this issue.
