### ISSUE TITLE
Default keymap conflicts with build system - Ctrl+B needs to be pressed twice

### ISSUE THREAD

**Issue by PeterPablo** [facelessuser/HexViewer#49]
I had the same issue described [here](https://forum.sublimetext.com/t/i-need-to-press-b-twice-to-run-the-build-system/11470) and fixed it by adapting my keymap, as described [here](http://stackoverflow.com/a/25923712/691487).
Is this a known issue/limitation?

Version: ST3, Build 3114

**Comment by facelessuser** [comment]
That is just a limitation of Sublime's keymap API.  As soon as you create a shortcut that requires you to press a key sequence, that first key combo in the sequence can no longer be used by itself.

You don't have to use the shortcuts I give in the example; you can use different ones.  I honestly build from a terminal...it's just they way I usually work, so I don't really bother with the build system in Sublime.  I honestly don't map those keys on my system like that anymore either but just use the command palette.

I know sublime uses `ctrl+k` as the start of a sequence, maybe you can use that instead of `ctrl+b`.  This is why I don't release with the keys actually defined, I don't want to conflict with peoples keymap setups.

**Comment by facelessuser** [comment]
As this question has been answered, I am closing this.

**Comment by PeterPablo** [comment]
Thank you @facelessuser!
