### ISSUE TITLE
Export Bin not working

### ISSUE THREAD

**Issue by kiran0553** [facelessuser/HexViewer#50]
Am using sublime text 3 in windows 10 and when I try to use the Export Bin command, its just creating another text file with same contents in it. And I can read it with regular notepad.

**Comment by facelessuser** [comment]
What are you expecting it to do?  The export function says `export bin`.  So if you were to edit the hex data and export it, it would be a binary file with your changes.  If you make no changes and export, then you will just have a clone of the binary file.  Maybe you were expecting something else?

**Comment by facelessuser** [comment]
Please respond or I will have to close this issue.  It does me no good to leave an issue open where I cannot get more info from the originator to try and help them solve their issue.

**Comment by kiran0553** [comment]
Please close the issue. I was just learning things and assumed something
else. Your response gave me good info to proceed further. Thanks for that.
And Thank you for the wonderful application.
ᐧ

**Comment by facelessuser** [comment]
Okay, just for anyone else.  If you read a text file in binary form, you will see the hex data, if you recreate the binary file with that hex data (export bin), you will get a text file again.  The text file is the binary file.  The reason we can view it has text is because editors can interpret the binary data and display it as such.

If you want to save the hex representation of the view, you can do that, just select the normal Sublime save to save the view away as a text file, then you will have the hex representation, but that is different. Than export that will take the actual hex data and reconstruct the binary file.  If that binary file was text data, the binary will be recognized as a text file by editors etc.

I will close this issue.
