### ISSUE TITLE
Ability to insert bytes?

### ISSUE THREAD

**Issue by keithjjones** [facelessuser/HexViewer#52]
I don't see the ability to add bytes to a file.  You can change them, but not add them.

**Comment by facelessuser** [comment]
Yup, that pretty much sums it up :smile:.

Depending on the size of the binary, this can be a pain due to how the everything is in the same view: the address, the hex, the ASCII representation, etc.  The whole thing from that point on needs to be re-output and then re-rendered in the view.  In large files, this could be annoying.  When I wrote this, it was mainly to look at binary files.  Later I decided to add the ability to edit bytes in place, but when I do serious editing, I usually open the bin in an external editor, or script a solution if it is something more extensive.

Could I add the ability? Sure.  Will I?  I don't know, I haven't been motivated yet so far, and this is mainly because I have yet to need that functionality.  As I mentioned earlier, serious editing usually gets deferred to a script or a dedicated tool  (the right tool for the job and all that).

I'm also a selfish programmer; mainly because I do this all in my free time.  I write what I want to use and then make that publicly available.  I usually don't mind adding small things that maybe I don't use, or merging in another's work if it makes sense and doesn't get in the way of how I use it, or the task seems fun or interesting or will make my job maintaining the project easier, but outside of that...

I guess if a lot of people really desired the functionality, then maybe, but I honestly feel a good dedicated text editor is better for these kind of things.  This is mainly due to the limitations in presenting the info through the available medium.  If the access to UI elements was for rich, then maybe I would be more inclined to implement insertion/deletion.

**Comment by keithjjones** [comment]
That is totally understandable, I tend to be the same way with the projects I work on.  You only can work on things you need when you do it for free, most of the time.

The reason I was looking for the ability is because Emacs supports it, but not very well.  I was hoping to find a decent hex editor for all 3 platforms that would insert along with change.  That's what led me to you, as you seem to have the best hex viewer for sublime out there.

I'd have to really dig into the product to help you.  My sublime experience started today, so I have a ways to go.

Thanks for providing the functionality to begin with!

**Comment by facelessuser** [comment]
As I don't currently plan to implement this, I am closing this issue.
