### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by TPMoyer** [facelessuser/HexViewer#53]
documentation allows dumb-heads to become frustrated.
Please include a "how to invoke"  line in your documentation.    
     tools... packages...  hex viewer...   toggle hex view (or other option)

**Comment by facelessuser** [comment]
All commands should be available from the command palette as listed in the [documentation](http://facelessuser.github.io/HexViewer/usage/#commands).  Are you unsure what the command palette is?  The term command palette is a general Sublime Text term, and it is assumed that people are generally familiar with it.  But if you are not, let me know.

Another thing is that I don't know if there is some other issue.  If you know what the command palette is, do you not see the commands in the command palette?  Did you restart Sublime Text after installing HexViewer, if not, try that.  If you still don't see the commands, do you see errors in the console?  If you don't know what the console is, let me know.

**Comment by TPMoyer** [comment]
Hey Isaac:
     Had tried to follow the clues you had included in the documentaiton,
however the hot-key sequence from
http://docs.sublimetext.info/en/latest/reference/command_palette.html failed
me in my windows 7 sublime text 3 instance (pulls up package control
instead of the command_palette).   Can one pull up the command_pallette
with a sequence of mouce clicks through the "File, Edit,
Selection,Find,View, Goto, Tools, ..." series of pulldowns

Have no other issues.
Works great, after finding a way in:   tools... packages...   Hex Viewer...
  Toggle Hex View
Your package is a killer add to the recurrent "sublime-text is better than
VI" discussion.

Thank you

**Comment by facelessuser** [comment]
>  Had tried to follow the clues you had included in the documentaiton,
however the hot-key sequence from
http://docs.sublimetext.info/en/latest/reference/command_palette.html failed
me in my windows 7 sublime text 3 instance (pulls up package control
instead of the command_palette). 

It's supposed to work.  Unfortunately that may require support form the Sublime Text team.  Not sure why that wouldn't be working for you.  I would try posting the question on the forum and see if someone has any ideas.  That would not be caused by HexViewer though.

>  Can one pull up the command_pallette
with a sequence of mouce clicks through the "File, Edit,
Selection,Find,View, Goto, Tools, ..." series of pulldowns

Yes, `Tools->Command Palette`.

> Your package is a killer add to the recurrent "sublime-text is better than
VI" discussion.

Thank you :smile:.

**Comment by strength14** [comment]
Can you close my account please

**Comment by facelessuser** [comment]
@strength14, what?
