### ISSUE TITLE
Improve Basic Usage Guide

### ISSUE THREAD

**Issue by srcspider** [facelessuser/HexViewer#60]
The term toggle it from your "Command Pallet" is really easily misleading. I don't think many people think of it as the command pallet just as "the Ctrl+Shift+P thing." 

Please add a section to the docs or github readme that just says: 

**To use press Ctrl+Shift+P then type "HexViewer" for commands.**

That's all we really needs to know.

Also don't see mention of a very major limitation. If you actually want to view jpeg's, png's etc in it you actually have to change the extension of the file (such as adding .hex at the end) since you forbid viewing them otherwise if I'm not mistaken. Somewhat confused why this is the case. Every time I want to view something in a hex editor it's usually not your regular text file.

**Comment by facelessuser** [comment]
> The term toggle it from your "Command Pallet" is really easily misleading. I don't think many people think of it as the command pallet just as "the Ctrl+Shift+P thing."

I'm not sure exactly what you are referring to, but you are welcome to submit a pull request for review if you think you can improve upon the documentation.

> Also don't see mention of a very major limitation. If you actually want to view jpeg's, png's etc in it you actually have to change the extension of the file (such as adding .hex at the end) since you forbid viewing them otherwise if I'm not mistaken.

There is nothing inherently in HexViewer that prevents it from viewing images as hex.  A matter of fact, HexViewer used to open images as Hex (though I've never really needed to view images as hex).  The reason why it doesn't now is because Sublime intercepts images and opens them in preview views.  This views do not behave like normal views, and I cannot retrieve image paths or image content from those views.  Why Sublime does this is beyond me.  If you were able to disable this special image preview mode, HexViewer would have no trouble with it.

I am open to mention of it being added into the documentation though.  Again pull requests are welcome.

**Comment by srcspider** [comment]
I assumed it was intentional since it doesn't seem to block the generate hash option, but I guess that's just an oddity.

**Comment by facelessuser** [comment]
Hash shouldn't be able to access the image data in a preview.  I probably just didn't but a check on it. I'll take a look at hash sometime and see.

**Comment by facelessuser** [comment]
Going through old issues.  Image support workaround has been added for a bit now.  You can now toggle hex view on images, but since they are not normal views with normal view events, I can't auto detect and convert, but I'd prefer not to anyways as I like being able to preview images, and then hex view them when I need to.

As for hash commands available for views, "Generate Hash" is not specific to a view but is an command that gives you access to the underlying hash generation.  It allows you to enter in any text and have it hashed.

The other hash command allows you to hash a selection in a view, but since you can't select anything in an image, I feel it should be reasonably obvious that that command doesn't apply to images.

Anyways, as there is no actionable item here (due to hex view for images available again), I am closing.
