### ISSUE TITLE
Can't install/load HexViewer and no errors

### ISSUE THREAD

**Issue by rainabba** [facelessuser/HexViewer#61]
Running SublimeText 3 build 3126:

Package Manager doesn't list "HexViewer" so I GIT cloned into my packages folder as instructed and I do see `C:\Program Files\Sublime Text 3\Packages\HexViewer\dependencies.json` along with ~25 other files (visual guestimate). I've also restarted Sublime (closed all instances and checked processes to be sure).

Even installed that way, "HexViewer" doesn't come up in my command pallette nor do I see anything under tools->packages.

Console is empty and I see no signs of loading errors (or HexViewer loading at all).

Any idea what else I could check or what I might have missed?

**Comment by facelessuser** [comment]
If package control is not showing HexViewer it is because you already had it installed.  Delete HexViewer in the `Packages` **and** `Installed Packages` folder and try again.  Installing manually requires some extra steps.

If you chose to install manually (not recommended) please read the steps in the documentation: http://facelessuser.github.io/HexViewer/installation/.
