### ISSUE TITLE
Natural editing

### ISSUE THREAD

**Issue by TheGag96** [facelessuser/HexViewer#64]
I understand that actually editing files is very limited right now, I assume due to the limitations of Sublime plugins. How much further could you go with it though? How difficult would being able to at least directly overwrite be? Could inserting naturally ever be implemented? 

Regardless, this plugin is just so cool! Being able to perfectly hex edit in Sublime would be a *huge* QoL improvement for the stuff I do.

**Comment by facelessuser** [comment]
The main reason I don't allow inserts and deletes is because you have essentially re-render the whole view. It could be done, but in large binary files, it would be kind of painful. I rarely have to directly edit a binary, and even more rare to modify binary size via inserts or deletes, so if I do, I usually would break out a dedicated binary editor or write a script.

**Comment by TheGag96** [comment]
Hmm, well alright then. When it comes to dedicated hex editors, what's your go-to? I've been looking for something to replace HxD that doesn't cost money and I'm coming up with nothing lol.

**Comment by facelessuser** [comment]
To be honest, I usually just write a script to do serious editing.  This is mostly because in the cases I need to edit binary files, I'm parsing a binary structure that isn't easy to do by just eyeballing it in a viewer.  Analyzing yes, but I am usually changing lots of different things and an automated script makes way more sense in those cases. That's the kind of hex editing I am usually doing, so freeform editing just isn't a requirement for me.  Other times I just need to edit something in place, so I don't really use external hex editors all that often.

As the name implies, I wrote HexViewer mainly as a viewer.  I did add in place editing later.  If the API was a bit different, I probably wouldn't mind adding full editing, but it just wouldn't work how I'd like with current limitations.
