### ISSUE TITLE
Sometimes incorrect character code highlighting

### ISSUE THREAD

**Issue by rterekhov** [facelessuser/HexViewer#66]
![hexviewer](https://user-images.githubusercontent.com/5381279/49939388-029ef700-fedd-11e8-9dd7-c0ae946808f7.png)

**Comment by facelessuser** [comment]
I would need a simple reproducable scenario to debug this. If I'm able to reproduce this, I'll gladly offer a fix.

**Comment by rterekhov** [comment]
Here is the file i used: [HexViewer.txt](https://github.com/facelessuser/HexViewer/files/2676234/HexViewer.txt)

**Comment by facelessuser** [comment]
Thanks, I'll take a look and let you know if I need more information.

**Comment by facelessuser** [comment]
Turns out there is a bug with Sublime's API. Specifically with `extract_scope`. It was extracting the scope, but the start was shifted 1 to the left, but only when the line didn't end with a newline...which is weird.

While Sublime contributed to the wrong character getting selected, we also had a bug on lines that end with newline as well, specifically dealing with the last character on the line. When there was no newline, we would not select the last character.

So it was half us and half buggy Sublime API.  The good news is that I was able to fix our issue, and workaround the Sublime issue.
